### ISSUE TITLE
configuration object?

### ISSUE THREAD

**Issue by hluz** [kaoskeya/meteor-accounts-admin-ui-bootstrap-3#2]
The docs mention accountsAdminUiConfiguration as the configuration object, but he code appears to use AccountsAdmin.config, although none works... which way?
Not sure if part of same problem, but the edit and delete icons are also there for the logged-in admin...

**Comment by kaoskeya** [comment]
Hey,

The `AccountsAdmin.config` here is for the configuration of this package and is in no way connected to meteor's `Accounts.ui.config`.
Also, I think the admin functionality to edit/delete the users is an important functionality.

Please do let me know if the above does not clarify or if I've understood your issue incorrectly.

Also, this is not my package, I've forked it front andylash and have only done very minor fixes so as to push it to atmosphere as I needed the latest version of this package for an app. I do have a few fixes and changes planned though.

**Comment by kaoskeya** [comment]
Hey,

You might want to consider using https://atmospherejs.com/kaoskeya/meteor-accounts-autoform-admin, a new package I have written from scratch. 

Feel free to open an issue there is you come across any issues.

Thank you.
