### ISSUE TITLE
Doesn't show Name, Account Name

### ISSUE THREAD

**Issue by ahmetcetin** [kaoskeya/meteor-accounts-admin-ui-bootstrap-3#3]
It doesn't show Name and Account Name fields:
![screenshot_21_04_15_15_09](https://cloud.githubusercontent.com/assets/5046786/7252836/7fe006a6-e838-11e4-943d-7974dfc1ab7c.png)

After clicking the edit icon, when I try to change the User name field, it gives the following error in the cmd, and it doesn't update username:
![1__node](https://cloud.githubusercontent.com/assets/5046786/7252884/d4eac3d4-e838-11e4-8295-a46e20159a4a.png)

Any idea, am I doing anything wrong?

**Comment by kaoskeya** [comment]
Hey, just pushed an update. The name edit should work alright now.

As for the name and account name, I am unsure what is happening. Could you try running `Meteor.users.find().fetch()` in your console to see if the username/email fields are actually available on the client?

**Comment by ahmetcetin** [comment]
Wow, thx for quick reply. Now it looks it works. Here is the console output after running Meteor.users.find().fetch():
![developer_tools_-_http___localhost_9000_admin](https://cloud.githubusercontent.com/assets/5046786/7253680/b0120f58-e83e-11e4-80a2-c74ce690f6e4.png)
Now, I constantly get the following exception in cmd:
![1__node](https://cloud.githubusercontent.com/assets/5046786/7253717/d5e6aae0-e83e-11e4-9482-947ece3ffa86.png)

One more question if I don't bother: How can I add/change the fields shown in the users table? Can I show the profile fields that I define?

**Comment by kaoskeya** [comment]
Hey,

Not too sure how the package us written. I'll read into the code a bit and let you know if the customization is possible currently and also the error message.

Thank you.

**Comment by kaoskeya** [comment]
Hey,

A quick fix for this, you will have to put the following code in a file in your client side.

AccountsAdminFields will be the variable you want to modify to have your custom fields.

```
var getRoles = function(value) {
  if (_.isArray(value)) {
    return value.join(',');
  } else if (_.isObject(value)) {
    var roles = [];
    if (_.isArray(value[Roles.GLOBAL_GROUP])) {
      value[Roles.GLOBAL_GROUP].forEach(function(role) {
        roles.push(role);
      });
    }
    _.keys(value).forEach(function(group) {
      if (group !== Roles.GLOBAL_GROUP) {
        value[group].forEach(function(role) {
        roles.push(role);
        });
      }
    });
    return roles.join(',');
  }
};

var getEmail = function(value, user) {

  if (user.emails && user.emails.length)
    return user.emails[0].address;

  if (user.services) {
    //Iterate through services
    user.services.forEach(function(serviceName) {
      var serviceObject = user.services[serviceName];
      //If an 'id' isset then assume valid service
      if (serviceObject.id) {
        if (serviceObject.email) {
          return serviceObject.email;
        }
      }
    });
  }
  return "";
};

AccountsAdminFields = [{
    key: '',
    label: '',
    tmpl: Template.accountsAdminControlPanel
}, {
    key: 'username',
    label: 'username'
}, {
    key: 'profile.name',
    label: 'Name'
}, {
    key: 'emails.0.address',
    label: 'Email',
    fn: function(value, user) {
        return getEmail(value, user);
    }
}, {
    key: 'roles',
    label: 'Roles',
    fn: function(value) {
        return getRoles(value);
    }
}, {
    key: 'createdAt',
    label: 'Created?',
    fn: function(value) {
        return value && value.toDateString();
    }
}];

if (AccountsAdmin.config.userStatus) {
    fields.push({
        key: 'status.lastLogin.date',
        label: 'Last Login',
        fn: function(value) {
            return value && value.toLocaleString();
        }
    });
    fields.push({
        key: 'status.online',
        label: 'Online?'
    });
}
```

I'm not too happy with a few things, just consider this a quick fix. I'll have to find time and rewrite this package sometime.. 

Let me know if the above works. Also the console log screenshot you've sent, has only one user available on the client, could you run it in the page that used this admin panel and see if all the users with relevant fields are available on the client?

**Comment by kaoskeya** [comment]
Hey,

If you are using https://atmospherejs.com/kaoskeya/meteor-admin, you might want to consider using https://atmospherejs.com/kaoskeya/meteor-accounts-autoform-admin, a new package I have written from scratch..

Thank you.
